### ISSUE TITLE
Idea: Easy access copy buttons for password and/or username

### ISSUE THREAD

**Issue by GrayJacketStudios** [oegea/passager-password-manager#27]
Pain: As an user i want a fast access point to my password, maybe without the neccessity of seeing it (1 click vs 3/4 clicks).

Description: Create a button with a tooltip text that hint that you can copy your password to the clipboard from there.
In that button you can press it, and the password would be automatically copied to your clipboard if successfull. (maybe hint it with a toast type notification)

![fast mockup](https://user-images.githubusercontent.com/29789445/152797624-4396aa9a-3d6c-43ba-97ff-6860629f8fc5.png)

**Comment by oegea** [comment]
Adapted to the new issue format: https://github.com/oegea/passager-password-manager/issues/51
