### ISSUE TITLE
WIP: Option for automatic password generation

### ISSUE THREAD

**Issue by GrayJacketStudios** [oegea/passager-password-manager#28]
Pain: As an user, i dont have all the creativity to create different passwords for my different apps and websites, with some of them having special restrictions.

US Description: We need to create an option to automatically generate a strong password.

- The automatically generated password must complie with the minimun industry standard for a secure password (there is not an ISO standard 😞)
- There must be a button for advanced options, that when pressed must show the following options:
1. Minimum of characters (cant be lower than 1, or greater than the maximum)
2. Maximum of characters (Cant be lower than the minimum, or greater than... **define maximum**
3. Only numbers password
4. Only alphanumeric password (exclude special characters)

**Comment by prizzio** [comment]
yo uso mucho una pagina que tiene un estilo bastante basico pero que cumple
bien:

[image: image.png]

**Comment by prizzio** [comment]
Era esta pagina => https://passwordsgenerator.net/

**Comment by oegea** [comment]
@prizzio Yep. That's great. Maybe we should look for something more compact and visually nicer, but I think that's the idea.

Thank you for your contribution guys :)

**Comment by oegea** [comment]
Will close this to reflect it on a new issue following the new template
