### ISSUE TITLE
Description label on confirmation dialogs

### ISSUE THREAD

**Issue by oegea** [oegea/passager-password-manager#49]
# Feature issue

## 🔧 Is your feature request related to a problem? Please describe

When a confirmation dialog is displayed asking for confirmation on important actions (i.e. when deleting a folder), it will be useful to display a description of which action is being confirmed and additional useful information, for example if the action is irreversible or not.

## 📢 Describe the solution you'd like

It will be ideal to adapt the confirmation dialog component to be able to receive a description, and display it inside the dialog.

## 💡 Describe alternatives you've considered

Based on feedback of various users, displaying a basic description seems enough.

## 💬 Additional context

We have received this suggestion from many users, so it is considered a validated proposal.
This is the current visual aspect of a confirmation dialog:

![image](https://user-images.githubusercontent.com/16169223/193133080-108296a9-5de6-4ded-9d82-84766bd15bd0.png)

The scope of this issue is limited to display a message under the dialog's title.

**Comment by mau211** [comment]
@oegea I am interested in picking this up!

**Comment by oegea** [comment]
Hello @mau211,

Thank you for your interest in contributing to Passager. 😄 
The component where we want to add a description label is this 👉 `https://github.com/oegea/passager-password-manager/blob/main/src/components/organisms/ConfirmationDialog/index.js`

It should be an optional prop to display a simple description. 

Let me know if I can help you in any way! 🙏

**Comment by oegea** [comment]
(Btw, just assigned this issue to you)

**Comment by oegea** [comment]
Hello @mau211,

We're trying to solve your permission issues. I apology for them.

Meanwhile, could you please check this?

1. Be sure that you are properly logged within the git cli.
2. If problems persist, please try to make a fork of Passager, and push your branch to your forked version of the project.
3. Then, create a new PR from your forked repo.

I know this is not ideal. We're working to solve it (We're not experts in configuring github permissions, and seems that we have applied strict rules accidentally). But meanwhile maybe it could help.

**Comment by oegea** [comment]
Closing this issue as it has been completed.
