### ISSUE TITLE
Copy button to rapidly copy a password

### ISSUE THREAD

**Issue by oegea** [oegea/passager-password-manager#51]
# Feature issue

## 🔧 Is your feature request related to a problem? Please describe.
When a user access to an existing password to copy and use it, it is a bit tricky and tedious to have to manually select the password from the text input field and copy its value.

## 📢 Describe the solution you'd like
It will be much more nice to have a copy button within the password and username text fields, to rapidly copy them and access the desired website.

## 💡 Describe alternatives you've considered
Create a new input component (wrapping the input text component) to add a copy  button, similar to the following examples:

![image](https://user-images.githubusercontent.com/16169223/193136799-9be67eb9-51fc-4782-bdb9-7732258a9114.png)

![image](https://user-images.githubusercontent.com/16169223/193136822-af75d174-1be7-487e-b9e0-1f968fa32ae3.png)

It is important to have a usable and understable interface.

## 💬 Additional context
This is the current password form dialog:

![image](https://user-images.githubusercontent.com/16169223/193136583-b8d6c3e8-ed02-4650-a520-69205eee0db5.png)

**Comment by varun7singh** [comment]
im working on this

**Comment by oegea** [comment]
All yours! Let me know if you need anything. @varun7singh

**Comment by oegea** [comment]
@varun7singh I have accepted your PR and merged it :) 

Thank you for your contribution, I'm closing this issue to mark it as completed.
