### ISSUE TITLE
Create tests for the atom/alertButton component

### ISSUE THREAD

**Issue by oegea** [oegea/passager-password-manager#52]
# Feature issue

## 🔧 Is your feature request related to a problem? Please describe.
Components should have been covered by unit tests to increase code stability and deploy confidence.

## 📢 Describe the solution you'd like
Create a unit test for `atom/alertButton`.

## 💡 Describe alternatives you've considered
There are not additional alternatives.

## 💬 Additional context
Example of an already existing test: https://github.com/oegea/passager-password-manager/blob/main/src/components/atoms/Button/Button.test.js

**Comment by joshalling** [comment]
I can do this

**Comment by oegea** [comment]
All yours! @joshalling 

Let me know if you need anything :)

**Comment by GrayJacketStudios** [comment]
closing it after the PR #77
