### ISSUE TITLE
Create tests for the atom/dialog component

### ISSUE THREAD

**Issue by oegea** [oegea/passager-password-manager#54]
# Feature issue

## 🔧 Is your feature request related to a problem? Please describe.
Components should have been covered by unit tests to increase code stability and deploy confidence.

## 📢 Describe the solution you'd like
Create a unit test for `atom/dialog`.

## 💡 Describe alternatives you've considered
There are not additional alternatives.

## 💬 Additional context
Example of an already existing test: https://github.com/oegea/passager-password-manager/blob/main/src/components/atoms/Button/Button.test.js

**Comment by HamzaRahmani** [comment]
I can give this a try.

**Comment by HamzaRahmani** [comment]
@oegea; With my second test I'm tryingto validate that clicking on the background closes the Dialog. 
Here's what I currently have, any idea as to what I'm doing wrong?
https://github.com/HamzaRahmani/passager-password-manager/blob/tests-atom-dialog-component/src/components/atoms/Dialog/Dialog.test.js#L17

**Comment by oegea** [comment]
@HamzaRahmani Please give me some hours and I’ll deeply review and test your proposal.

**Comment by oegea** [comment]
Hello @HamzaRahmani 

Test is not passing because you are not properly selecting the dialog background.

Here goes an approach about how to achieve it:

First, add a `data-testid` prop to the background element in `src/components/atoms/Dialog/Dialog.js`:

```
return <>
        <OverlayBackground data-testid="dialog-background" data-isdialogbackground="true" onClick={(event) => { 
            if (_isDialogBackground(event.target)) { onClose(); } 
        }}>
            <Dialog>
                {children}
            </Dialog>
        </OverlayBackground>
    </>
```

(Note that the only thing I changed is that I've added the `data-testid` param)

Then, you can modify your current test with the following:

```
test('dialog should close when the background is clicked', () => {
  const handleClose = jest.fn();

  // Arrange
  render(<AtomDialog onClose={handleClose}>{DIALOG_CHILDREN}</AtomDialog>);

  const dialogBackground = screen.getByTestId("dialog-background");
  expect(dialogBackground).toBeInTheDocument();

  // Act
  fireEvent.click(dialogBackground);

  // Assert
  expect(handleClose).toHaveBeenCalledTimes(1);
});
```

This is because the Dialog component always render its own background. Yo don't need to wrap the component within another background. Additionally, we select the background div with the `byTestId` selector, and simulate a click event on it, to execute the `onClick` callback.

Hope that this helps! Let me know if anything else is needed.

**Comment by HamzaRahmani** [comment]
Thanks, really informative! I'll be making the changes and cutting a PR soon.

**Comment by HamzaRahmani** [comment]
I created the #83. Any feedback would be appreciated.
