### ISSUE TITLE
Apply a specific lint code style

### ISSUE THREAD

**Issue by oegea** [oegea/passager-password-manager#72]
# Feature issue

## 🔧 Is your feature request related to a problem? Please describe.
Currently we are using the lint configuration that comes with `create-react-app` utility.
However, it is not enough. It would be great to have es lint with a code style applied, and enforce to follow it. (Adding a lint check before commiting changes using husky)

## 📢 Describe the solution you'd like
1. Configure es lint to apply a specific code style and fix errors.
2. Run lint command before commiting changes (create a husky hook)

## 💡 Describe alternatives you've considered
N/A

## 💬 Additional context
All these changes need to be performed without ejecting create react app.

**Comment by Vinitvh** [comment]
Hi, I would like to attempt this.

**Comment by oegea** [comment]
@Vinitvh all yours!

**Comment by Vinitvh** [comment]
@oegea Do you want me to comment husky hook which applies linter? Otherwise, I would be committing all the files with changes in styles. I think you can uncomment for testing purpose.

**Comment by oegea** [comment]
Feel free to apply all changes in your PR. I’ll test everything before merging, so no problem =D You can add the husky hook.
