### ISSUE TITLE
Refactor copy  password buttom

### ISSUE THREAD

**Issue by GrayJacketStudios** [oegea/passager-password-manager#73]
# Feature issue

## 🔧 Is your feature request related to a problem? Please describe.
The new changes pushed by #66 was in the same component, when it should have added the buttom in its own component.
The buttom is really close to the input box, so it would be nice to have some of space
![imagen](https://user-images.githubusercontent.com/29789445/193407776-10306f03-8423-4e72-80ee-2cc80cc3e3df.png)

## 📢 Describe the solution you'd like
Refactor the button to its own component.
Add a style rule to have a padding with other components.

**Comment by Misterr-H** [comment]
@GrayJacketStudios 
hey are u working on it?

**Comment by GrayJacketStudios** [comment]
> @GrayJacketStudios hey are u working on it?

yep!

**Comment by GrayJacketStudios** [comment]
Fixed the error label to show at the end and not at the side 
![imagen](https://user-images.githubusercontent.com/29789445/193408913-4f079d08-e139-4467-b8fb-f3143bc962b3.png)

**Comment by GrayJacketStudios** [comment]
Moved the button to its own component, and gave it a little padding

**Comment by GrayJacketStudios** [comment]
Added the copy button to the username input too
![imagen](https://user-images.githubusercontent.com/29789445/193409159-3184a867-507f-4ae0-97a7-cd7c3fe5c092.png)
