### ISSUE TITLE
Display an additional message when deleting a password or a password folder

### ISSUE THREAD

**Issue by oegea** [oegea/passager-password-manager#76]
# Feature issue

## 🔧 Is your feature request related to a problem? Please describe.
We've recently modified the `ConfirmationDialog` component (which is a component that asks for confirmation before doing a risky action), to be able to show a description with additional information. Now the `ConfirmationDialog` component accepts a new `description` prop receiving an string.

Now, we need to apply that property in all places where  `ConfirmationDialog` is rendered.

## 📢 Describe the solution you'd like
`ConfirmationDialog` is rendered only in `organisms/DocumentsListRightPanel` component. When a password or a folder is being deleted.

We need to modify those places, and add a warning message.

## 💡 Describe alternatives you've considered
When a folder is being deleted, we should add the following message: 

* **English:** `This folder and ALL CONTAINED PASSWORDS WILL BE DELETED. This action cannot be undone. Are you completely sure that you want to delete this folder and its content?` 
* **Spanish:** `Esta carpeta y TODAS LAS CONTRASEÑAS CONTENIDAS SERÁN ELIMINADAS. Esta acción no puede ser revertida. ¿Estás completamente seguro de que quieres eliminar esta carpeta y su contenido?`

When a specific password is being deleted, we should display this message:

* **English:** `The selected password will be deleted. This action cannot be undone. Are you completely sure that you want to delete it?` 
* **Spanish:** `La contraseña seleccionada será eliminada. Esta acción no puede ser revertida. ¿Estás completamente seguro de que quieres eliminar esta contraseña?`

(btw, my English is not perfect. So grammar and style suggestions are welcome)

## 💬 Additional context

To simplify this issue, please find the following code snippets within `organisms/DocumentsListRightPanel` to know where to place these literals:

**Folder deletion**

```
            {
                showConfirmationDialog && 
                <ConfirmationDialog 
                    onAccept={() => onDelete()} 
                    closeDialog={()=>setShowConfirmationDialog(false)} 
                /> 
            }
```

**Password deletion**

```
            {
                deleteState.showDialog &&
                <ConfirmationDialog 
                    onAccept={() => onDeletePassword()} 
                    closeDialog={()=>setDeleteState({showDialog: false, password: null})} 
                /> 
            }
```

**Comment by varun7singh** [comment]
Im solving this

**Comment by oegea** [comment]
Closing
