### ISSUE TITLE
UX Improvement: When editing an existing password, do not auto-focus the title field

### ISSUE THREAD

**Issue by oegea** [oegea/passager-password-manager#87]
# Feature issue

## 🔧 Is your feature request related to a problem? Please describe.
When the new password form is opened, the name field (the first one, which gives a identificable name to the password) is focused. This is great, because the user doesn't have to manually focus the field to start writing.

However, the behaviour is the same when the password form is opened in edit mode. This is not ideal, because the user is normally looking to copy its username and/or password, and the focus on the field distracts they from that mission.

Additionally, when this happens in the mobile app, it is very annoying, as the mobile device keyboard opens, taking a lot of place from the screen.

## 📢 Describe the solution you'd like
Do not auto-focus the password name field when editing a password.

## 💡 Describe alternatives you've considered
Do not auto-focus the password name field when editing a password.

## 💬 Additional context
This is the password creation and edition form: 

It is located at. `organisms/PasswordFormDialog`. Look at the line 135,  `autoFocus` prop should be only included if form is not ran in edit mode.

<img width="452" alt="Captura de Pantalla 2022-10-02 a las 17 39 25" src="https://user-images.githubusercontent.com/16169223/193462695-296cded4-39e9-499f-8c72-43af90e0fb1d.png">

**Comment by SoldierCorp** [comment]
Hi @oegea , I would like to work on this issue.

**Comment by oegea** [comment]
All yours @SoldierCorp
